export enum MediaFolderEnum {
  ADMIN = 'admin',
  EVENT = 'event',
  FAMILY = 'family',
  APP_USER = 'app-user',
  JOB = 'job',
  LOVS = 'lovs',
  NEWS = 'news',
  TEMPLE = 'temple',
  GALLERY = 'gallery',
  MEDIA_FOLDER = 'media-files',
  MEDIA_FOLDER_PHYSICAL_PATH = `/home/mahendra/Mahendra/EatFit247/Project/eatfit247-v2/eatfit247-cms-api/media-files`,
  UPLOAD_FILE_PATH = `/home/mahendra/Mahendra/EatFit247/Project/eatfit247-v2/eatfit247-cms-api/media-files`,
  UPLOADS = 'uploads',
  DOWNLOADS = 'downloads',
  DIET_PLAN = 'diet-Plans',
  INVOICE = 'invoice',
  RECIPES = 'recipes',
}
