export enum NavigationPathEnum {
  HOME = '/',

  LOGIN = 'login',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_PASSWORD = 'reset-password',

  // LOV Master
  LOV_MASTER = 'lov-master',
  BLOOD_SUGAR = 'lov-master/blood-sugar',
  EATING_HABIT = 'lov-master/eating-habit',
  GENDER = 'lov-master/gender',
  HEALTH_PARAMETER = 'lov-master/health-parameter',
  LIFESTYLE = 'lov-master/lifestyle',
  MARITAL_STATUS = 'lov-master/marital-status',
  RELIGION = 'lov-master/religion',
  SLEEPING_PATTERN = 'lov-master/sleeping-pattern',
  TYPE_OF_EXERCISE = 'lov-master/type-of-exercise',
  URINE_OUTPUT = 'lov-master/urine-output',
  RECIPE_CATEGORY = 'lov-master/recipe-category',
  RECIPE_CUISINE = 'lov-master/recipe-cuisine',
  RECIPE_TYPE = 'lov-master/recipe-type',
  CALL_TYPE = 'lov-master/call-type',
  CALL_TYPE_NEW = 'lov-master/call-type/new',
  CALL_TYPE_EDIT = 'lov-master/call-type/edit',
  CALL_PURPOSE = 'lov-master/call-purpose',
  CALL_LOG_STATUS = 'lov-master/call-log-status',
  BLOG_CATEGORY = 'lov-master/blog-category',
  BLOG_AUTHOR = 'lov-master/blog-author',
  BLOG_COMMENTS = 'lov-master/blog-comments',
  FAQ_CATEGORY = 'lov-master/faq-category',
  ISSUE_CATEGORY = 'lov-master/issue-category',
  ISSUE_STATUS = 'lov-master/issue-status',
  PROGRAM_CATEGORY = 'lov-master/program-category',
  COUNTRY = 'lov-master/country',
  STATE = 'lov-master/state',
  ADDRESS_TYPE = 'lov-master/address-type',

  // Main Features
  MEMBERS = 'members',
  BLOGS = 'blogs',
  FAQ = 'faq',
  RECIPES = 'recipes',
  PROGRAMS = 'programs',
  PROGRAM_PLAN = 'program-plans',
  MEDIA_PRESS = 'media-press',
  REFERRER = 'referrer',
  FRANCHISE = 'franchise',
  POCKET_GUIDE = 'pocket-guide',
  CALL_LOGS = 'call-logs',
  ISSUES = 'issues',
  ADMIN_USER = 'admin-user',
}
