FROM node:22-alpine AS build
RUN apk add g++ make py3-pip
WORKDIR /home/app
RUN mkdir -p eatfit247-web && mkdir -p shared-library && mkdir -p infra
COPY ./infra/ ./infra/
COPY ./shared-library/package*.json ./shared-library/
RUN npm --prefix shared-library install
COPY ./eatfit247-web ./eatfit247-web
RUN npm --prefix eatfit247-web install --legacy-peer-deps
COPY ./shared-library ./shared-library
RUN npm --prefix eatfit247-web run build

FROM nginx:latest AS ngi
COPY --from=build /home/app/eatfit247-web/dist/apps/main /usr/share/nginx/html
COPY /infra/nginx-client.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
