FROM node:22

# Install system dependencies and clean up in one layer to reduce image size
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    g++ \
    make \
    python3-pip \
    chromium && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /home/app

RUN mkdir -p shared-library
COPY shared-library/package.json shared-library/tsconfig.json shared-library/
COPY shared-library/src shared-library/src
RUN cd shared-library && npm install && npm run build

# Install server dependencies (including devDependencies for build)
COPY server_1/package*.json ./server_1/
RUN npm --prefix server_1 install

# Copy server source code
COPY server_1/ ./server_1/

# Build the server applications
RUN npm --prefix server_1 run build

# Expose ports
EXPOSE 3000
EXPOSE 3001