services:
  public-api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.server
    image: eatfit-server
    container_name: eatfit-public-api
    command: sh -c "cd server_1 && node dist/apps/public-api/main.js"
    restart: always
    volumes:
      - assets:/home/app/assets
    env_file:
      - main.env
    environment:
      API_PORT: '3000'
    ports:
      - "3000:3000"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/api/v2/public/health' ]
      interval: 20s
      retries: 5
      start_period: 5s
      timeout: 10s
  admin-api:
    image: eatfit-server
    container_name: eatfit-admin-api
    command: sh -c "cd server_1 && node dist/apps/admin-api/main.js"
    restart: always
    volumes:
      - assets:/home/app/assets
    env_file:
      - main.env
    environment:
      API_PORT: '3000'
    ports:
      - "3001:3001"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3001/api/v2/admin/health' ]
      interval: 20s
      retries: 5
      start_period: 5s
      timeout: 10s
#  client-web:
#    build:
#      context: ..
#      dockerfile: infra/Dockerfile.client
#    image: eatfit-client
#    container_name: eatfit-client-web
#    restart: always
#    volumes:
#      - ./eatfit24by7-admin.conf:/etc/nginx/conf.d/eatfit24by7.conf
#      - ./certs/eatfit24by7.key:/etc/ssl/certs/eatfit24by7.key
#      - ./certs/eatfit24by7.pem:/etc/ssl/certs/eatfit24by7.pem
#    ports:
#      - "443:443"
#    depends_on:
#      - public-api
  admin-web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.admin
    image: eatfit-admin
    container_name: eatfit-admin-web
    restart: always
    volumes:
      - ./eatfit24by7-admin.conf:/etc/nginx/conf.d/eatfit24by7.conf
      - ./certs/eatfit24by7.key:/etc/ssl/certs/eatfit24by7.key
      - ./certs/eatfit24by7.pem:/etc/ssl/certs/eatfit24by7.pem
    ports:
      - "80:443"
    depends_on:
      - admin-api

volumes:
  assets:
    driver: local