services:
  public:
    container_name: eatfit-server-public
    image: eatfit-server
    command: sh -c "cd server && node dist/apps/public-api/main.js"
    restart: always
    volumes:
      - assets:/home/app/assets
    env_file:
      - main.env
    environment:
      API_PORT: '3000'
    ports:
      - "8001:3000"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/api/v2/public/health' ]
      interval: 20s
      retries: 5
      start_period: 5s
      timeout: 10s
  admin:
    container_name: eatfit-server-admin
    image: eatfit-server
    command: sh -c "cd server && node dist/apps/admin-api/main.js"
    restart: always
    volumes:
      - assets:/home/app/assets
    env_file:
      - main.env
    environment:
      API_PORT: '3000'
    ports:
      - "8001:3000"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/api/v2/public/health' ]
      interval: 20s
      retries: 5
      start_period: 5s
      timeout: 10s
  web-app:
    container_name: eatfit-client
    image: eatfit-client
    restart: always
    volumes:
      - ./eatfit24by7.conf:/etc/nginx/conf.d/eatfit24by7.conf
      - ./certs/eatfit24by7.key:/etc/ssl/certs/eatfit24by7.key
      - ./certs/eatfit24by7.pem:/etc/ssl/certs/eatfit24by7.pem
    ports:
      - "443:443"
    depends_on:
      - core
  admin-app:
    container_name: eatfit-admin
    image: eatfit-admin
    restart: always
    volumes:
      - ./eatfit24by7-admin.conf:/etc/nginx/conf.d/eatfit24by7.conf
      - ./certs/eatfit24by7.key:/etc/ssl/certs/eatfit24by7.key
      - ./certs/eatfit24by7.pem:/etc/ssl/certs/eatfit24by7.pem
    ports:
      - "8090:443"
    depends_on:
      - core

volumes:
  assets:
    driver: local