services:
  core:
    container_name: eatfit247-cms-api
    image: eatfit247-cms-server
    command: sh -c "cd eatfit247-cms-api && node dist/main.js"
    restart: always
    volumes:
      - assets:/home/app/assets
    env_file:
      - main.env
    environment:
      API_PORT: '3000'
    ports:
      - "8001:3000"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3330/api/v1/health' ]
      interval: 20s
      retries: 5
      start_period: 5s
      timeout: 10s
  vsd-client:
    container_name: eatfit247-cms-client
    image: eatfit247-cms-client
    restart: always
    volumes:
      - ./eatfit247.conf:/etc/nginx/conf.d/eatfit247.conf
      - ./certs/eatfit247.key:/etc/ssl/certs/eatfit247.key
      - ./certs/eatfit247.pem:/etc/ssl/certs/eatfit247.pem
    ports:
      - "443:443"
    depends_on:
      - core

volumes:
  assets:
    driver: local