export enum ConfigParam {
  GST_ENABLED = "GST_ENABLED",
  CALL_LOG_ENABLED = "CALL_LOG_ENABLED",
  DIET_FEEDBACK_ENABLED = "DIET_FEEDBACK_ENABLED",
  SEND_WELCOME_MAIL = "SEND_WELCOME_MAIL",
  SEND_DIET_MAIL = "SEND_DIET_MAIL",
  IS_APP_AVAILABLE = "IS_APP_AVAILABLE",
  TAX_PERCENTAGE = "TAX_PERCENTAGE",
  DEFAULT_CURRENCY = "DEFAULT_CURRENCY"
}