export enum EmailTemplateEnum {
  DIET_PLAN = 'DIET_PLAN',
  INQUIRY_RESOLVED = 'INQUIRY_RESOLVED',
  INVOICE_PLAN = 'INVOICE_PLAN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  WELCOME_ADMIN = 'WELCOME_ADMIN',
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  POCKET_GUIDE_ASSIGNED = 'POCKET_GUIDE_ASSIGNED',
}

export enum EmailType {
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  WELCOME_ADMIN = 'WELCOME_ADMIN',
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  DIET_PLAN = 'DIET_PLAN',
  INQUIRY_RESOLVED = 'INQUIRY_RESOLVED',
  INVOICE_PRODUCT = 'INVOICE_PRODUCT',
  INVOICE_PLAN = 'INVOICE_PLAN',
}