export enum MediaForEnum {
  ADMIN = "admin",
  HOME = "home",
  MEDIA_FOLDER = "media-files",
  UPLOADS = "uploads",
  BLOG = "blog",
  BRAND = "brand",
  FRANCHISE = "franchise",
  MEMBER = "member",
  POCKET_GUIDE = "pocket-guide",
  PRESS_MEDIA = "press-media",
  PROGRAM = "program",
  RECIPE = "recipe",
  REFERRER = "referrer",
  BLOG_AUTHOR = "blog-author",
  BLOG_CATEGORY = "blog-category",
  BLOOD_SUGAR = "blood-sugar",
  CALL_PURPOSE = "call-purpose",
  CALL_TYPE = "call-type",
  EATING_HABIT = "eating-habit",
  GENDER = "gender",
  HEALTH_ISSUE = "health-issue",
  HEALTH_PARAMETER = "health-parameter",
  LIFESTYLE = "lifestyle",
  MARITAL_STATUS = "marital-status",
  NUTRITIVE = "nutritive",
  PROGRAM_CATEGORY = "program-category",
  RECIPE_CATEGORY = "recipe-category",
  RECIPE_CUISINE = "recipe-cuisine",
  RECIPE_TYPE = "recipe-type",
  RELIGION = "religion",
  SLEEPING_PATTERN = "sleeping-pattern",
  TYPE_OF_EXERCISE = "type-of-exercise",
  URINE_OUTPUT = "urine-output",
  PROMOTIONAL_MAIL = "promotional-mail",
  LEGAL_PAGE = "legal-page",
}

