"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MediaForEnum = void 0;
var MediaForEnum;
(function (MediaForEnum) {
    MediaForEnum["ADMIN"] = "admin";
    MediaForEnum["HOME"] = "home";
    MediaForEnum["MEDIA_FOLDER"] = "media-files";
    MediaForEnum["UPLOADS"] = "uploads";
    MediaForEnum["BLOG"] = "blog";
    MediaForEnum["BRAND"] = "brand";
    MediaForEnum["FRANCHISE"] = "franchise";
    MediaForEnum["MEMBER"] = "member";
    MediaForEnum["POCKET_GUIDE"] = "pocket-guide";
    MediaForEnum["PRESS_MEDIA"] = "press-media";
    MediaForEnum["PROGRAM"] = "program";
    MediaForEnum["RECIPE"] = "recipe";
    MediaForEnum["REFERRER"] = "referrer";
    MediaForEnum["BLOG_AUTHOR"] = "blog-author";
    MediaForEnum["BLOG_CATEGORY"] = "blog-category";
    MediaForEnum["BLOOD_SUGAR"] = "blood-sugar";
    MediaForEnum["CALL_PURPOSE"] = "call-purpose";
    MediaForEnum["CALL_TYPE"] = "call-type";
    MediaForEnum["EATING_HABIT"] = "eating-habit";
    MediaForEnum["GENDER"] = "gender";
    MediaForEnum["HEALTH_ISSUE"] = "health-issue";
    MediaForEnum["HEALTH_PARAMETER"] = "health-parameter";
    MediaForEnum["LIFESTYLE"] = "lifestyle";
    MediaForEnum["MARITAL_STATUS"] = "marital-status";
    MediaForEnum["NUTRITIVE"] = "nutritive";
    MediaForEnum["PROGRAM_CATEGORY"] = "program-category";
    MediaForEnum["RECIPE_CATEGORY"] = "recipe-category";
    MediaForEnum["RECIPE_CUISINE"] = "recipe-cuisine";
    MediaForEnum["RECIPE_TYPE"] = "recipe-type";
    MediaForEnum["RELIGION"] = "religion";
    MediaForEnum["SLEEPING_PATTERN"] = "sleeping-pattern";
    MediaForEnum["TYPE_OF_EXERCISE"] = "type-of-exercise";
    MediaForEnum["URINE_OUTPUT"] = "urine-output";
    MediaForEnum["PROMOTIONAL_MAIL"] = "promotional-mail";
})(MediaForEnum || (exports.MediaForEnum = MediaForEnum = {}));
//# sourceMappingURL=media-for.enum.js.map