export enum ShipmentStatusEnum {
  DRAFT = 'DRAFT',
  RATE_REQUESTED = 'RATE_REQUESTED',
  RATE_SELECTED = 'RATE_SELECTED',
  BOOKING_REQUESTED = 'BOOKING_REQUESTED',
  BOOKED = 'BOOKED',
  PICKUP_SCHEDULED = 'PICKUP_SCHEDULED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  RTO = 'RTO',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

