import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import { ProgramPlanModule } from '@server/modules/program-plan';
import { TaxEngineModule } from '@server/modules/tax-engine';
import {
  MstAdminUser,
  modelRegistry,
  MstCountry,
  MstPocketGuide,
  MstHealthIssue,
  MstIssueStatus,
  MstIssueCategory,
  MstCallType,
  MstCallPurpose,
  MstCallLogStatus,
  MstHealthParameter,
  MstHealthParameterUnit,
  MstGender,
  MstMaritalStatus,
  MstReligion,
  MstLifestyle,
  MstEatingHabit,
  MstTypeOfExercise,
  MstSleepingPattern,
  MstBloodSugar,
  MstUrineOutput,
  TxnAddress,
  MstPaymentMode,
  MstPaymentStatus,
  MstProgramPlan,
  MstProgram,
} from '@server/common';
import { TxnMember, TxnMemberPocketGuide, TxnMemberHealthIssue, TxnMemberIssue, TxnMemberIssueResponse, TxnMemberHealthParameterLog, TxnMemberHealthParameter, TxnAssessment, TxnMemberPayment, TxnMemberDietPlan, TxnMemberDietDetail } from './models';
import { MstReferrer } from '@server/common';
import { MstFranchise } from '@server/common';
import {
  MemberController,
  PublicMemberController,
  CallLogController,
  MemberPocketGuideController,
  MemberHealthIssueController,
  MemberBodyStatsController,
  MemberIssueController,
  MemberAssessmentController,
  MemberCallLogsController,
  MemberPaymentController,
  MemberDietPlanController,
  MemberDashboardController,
} from './controllers';
import {
  MemberService,
  MemberPocketGuideService,
  MemberHealthIssueService,
  MemberCallLogsService,
  MemberHealthParameterLogsService,
  MemberIssueService,
  MemberIssueResponseService,
  MemberAssessmentService, MemberPaymentService,
} from './services';
import { TxnMemberCallLog } from './models';
import { CallLogsModule } from '@server/modules/call-logs';
// Register models with the model registry
modelRegistry.register([
  TxnMember,
  TxnMemberPocketGuide,
  TxnMemberHealthIssue,
  TxnMemberIssue,
  TxnMemberIssueResponse,
  TxnMemberCallLog,
  TxnMemberHealthParameterLog,
  TxnMemberHealthParameter,
  TxnAssessment,
  TxnMemberPayment,
  TxnMemberDietPlan,
  TxnMemberDietDetail,
]);

@Module({
  imports: [
    // Import ProgramPlanModule to use ProgramService and ProgramPlanService
    ProgramPlanModule,
    CallLogsModule,
    TaxEngineModule,
    SequelizeModule.forFeature([
      TxnMember,
      TxnMemberPocketGuide,
      TxnMemberHealthIssue,
      TxnMemberIssue,
      TxnMemberIssueResponse,
      TxnMemberCallLog,
      TxnMemberHealthParameterLog,
      TxnMemberHealthParameter,
      TxnAssessment,
      TxnMemberPayment,
      TxnMemberDietPlan,
      TxnMemberDietDetail,
      MstReferrer,
      MstFranchise,
      MstCountry,
      MstAdminUser,
      MstPocketGuide,
      MstHealthIssue,
      MstIssueStatus,
      MstIssueCategory,
      MstCallType,
      MstCallPurpose,
      MstCallLogStatus,
      MstHealthParameter,
      MstHealthParameterUnit,
      MstGender,
      MstMaritalStatus,
      MstReligion,
      MstLifestyle,
      MstEatingHabit,
      MstTypeOfExercise,
      MstSleepingPattern,
      MstBloodSugar,
      MstUrineOutput,
      TxnAddress,
      MstPaymentMode,
      MstPaymentStatus,
      MstProgramPlan,
      MstProgram,
    ]),
  ],
  controllers: [
    MemberController,
    PublicMemberController,
    CallLogController,
    MemberPocketGuideController,
    MemberHealthIssueController,
    MemberBodyStatsController,
    MemberIssueController,
    MemberAssessmentController,
    MemberCallLogsController,
    MemberPaymentController,
    MemberDietPlanController,
    MemberDashboardController,
  ],
  providers: [
    MemberService,
    MemberPocketGuideService,
    MemberHealthIssueService,
    MemberCallLogsService,
    MemberHealthParameterLogsService,
    MemberIssueService,
    MemberIssueResponseService,
    MemberAssessmentService,
    MemberPaymentService
  ],
  exports: [
    MemberService,
    SequelizeModule,
  ],
})
export class MemberModule {
}
