/**
 * Email Type Enum
 * Defines all available email types for the email service
 */
export enum EmailType {
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  WELCOME_ADMIN = 'WELCOME_ADMIN',
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  DIET_PLAN = 'DIET_PLAN',
  INQUIRY_RESOLVED = 'INQUIRY_RESOLVED',
  INVOICE_PRODUCT = 'INVOICE_PRODUCT',
  INVOICE_PLAN = 'INVOICE_PLAN',
}

