export const GST_ENABLED = 'GST_ENABLED';
export const CALL_LOG_ENABLED = 'CALL_LOG_ENABLED';
export const DIET_FEEDBACK_ENABLED = 'DIET_FEEDBACK_ENABLED';
export const SEND_WELCOME_MAIL = 'SEND_WELCOME_MAIL';
export const SEND_DIET_MAIL = 'SEND_DIET_MAIL';
export const IS_APP_AVAILABLE = 'IS_APP_AVAILABLE';
export const TAX_PERCENTAGE = 'TAX_PERCENTAGE';
export const DEFAULT_CURRENCY = 'DEFAULT_CURRENCY';
