import { Module } from '@nestjs/common';
import { SequelizeModule } from '@nestjs/sequelize';
import {
  MstAdminUser,
  modelRegistry,
  MstHealthIssue,
  MstGender,
  MstBloodSugar,
  MstEatingHabit,
  MstLifestyle,
  MstMaritalStatus,
  MstReligion,
  MstSleepingPattern,
  MstTypeOfExercise,
  MstUrineOutput,
  MstHealthParameter,
} from '@server/common';
import {
  GenderController,
  BloodSugarController,
  HealthIssueController,
  EatingHabitController,
  LifestyleController,
  MaritalStatusController,
  ReligionController,
  SleepingPatternController,
  TypeOfExerciseController,
  UrineOutputController,
  HealthParameterController,
  PublicGenderController,
  PublicBloodSugarController,
  PublicHealthIssueController,
  PublicEatingHabitController,
  PublicLifestyleController,
  PublicMaritalStatusController,
  PublicReligionController,
  PublicSleepingPatternController,
  PublicTypeOfExerciseController,
  PublicUrineOutputController,
  PublicHealthParameterController,
} from './controllers';
import {
  GenderService,
  BloodSugarService,
  HealthIssueService,
  EatingHabitService,
  LifestyleService,
  MaritalStatusService,
  ReligionService,
  SleepingPatternService,
  TypeOfExerciseService,
  UrineOutputService,
  HealthParameterService,
} from './services';

// Models are registered in @server/common module

@Module({
  imports: [
    SequelizeModule.forFeature([
      MstGender,
      MstBloodSugar,
      MstHealthIssue,
      MstEatingHabit,
      MstLifestyle,
      MstMaritalStatus,
      MstReligion,
      MstSleepingPattern,
      MstTypeOfExercise,
      MstUrineOutput,
      MstHealthParameter,
      MstAdminUser,
    ]),
  ],
  controllers: [
    GenderController,
    BloodSugarController,
    HealthIssueController,
    EatingHabitController,
    LifestyleController,
    MaritalStatusController,
    ReligionController,
    SleepingPatternController,
    TypeOfExerciseController,
    UrineOutputController,
    HealthParameterController,
    PublicGenderController,
    PublicBloodSugarController,
    PublicHealthIssueController,
    PublicEatingHabitController,
    PublicLifestyleController,
    PublicMaritalStatusController,
    PublicReligionController,
    PublicSleepingPatternController,
    PublicTypeOfExerciseController,
    PublicUrineOutputController,
    PublicHealthParameterController,
  ],
  providers: [
    GenderService,
    BloodSugarService,
    HealthIssueService,
    EatingHabitService,
    LifestyleService,
    MaritalStatusService,
    ReligionService,
    SleepingPatternService,
    TypeOfExerciseService,
    UrineOutputService,
    HealthParameterService,
  ],
  exports: [
    GenderService,
    BloodSugarService,
    HealthIssueService,
    EatingHabitService,
    LifestyleService,
    MaritalStatusService,
    ReligionService,
    SleepingPatternService,
    TypeOfExerciseService,
    UrineOutputService,
    HealthParameterService,
    SequelizeModule,
  ],
})
export class AssessmentMasterModule {
}

