INSERT INTO txn_faqs (faq_id, faq_category_id, faq, answer, active, created_at, created_by, updated_at, modified_by,
                      created_ip, modified_ip)
VALUES (1, 1, 'How do I pay ?', 'The payment process is like that of Internet backing, transfer amount to bank.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (2, 1, 'Do I need to pay upfront or I can pay in installments ?',
        'Yes, you can avail EMI Facility as well. At the Checkout page, you will get the option of Credit Card EMI. This Facility is available for only Indian Credit Card Holders.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (3, 1, 'What happens after I pay up ?',
        'Once you are done with the payment, you can log in into My Account section using your password & click on ASSESSMENT. You will also have a link to the form in the welcome mails you would have received. You shall have to fill the form in detail and submit; after that you will get an email confirming receipt of the same.<br><br>\r\nYou can then view and download the E-KIT on your phone for quick future reference from the “ My account” section or on the email you have got, which has guides for dining out, alcohol consumption, it has FAQs, & the trackers.<br><br>\r\nThe mentor would have sent you any queries or documents needed for clarity before they plan a diet chart, if so check your mail and “My account section”.<br><br>\r\nYour program begins maximum within 24 hours of you enrolling. Mentor assigned shall get in touch with you immediately.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (4, 2, 'How does one join or enroll the online weight loss program at https://www.eatfit247.com?',
        'Enrolling is a simple process. After registering, you can select the program of your choice (If in doubt use the need assistance, or chat feature or use the video tutorial) and click on \"Buy Program\" and proceed with online payment.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (5, 3, 'What is Eatift247 all about?',
        'An online program for weight loss and other lifestyle conditions like Diabetes, PCOS, Thyroid, cholesterol etc.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (6, 3, 'How does the online program work?',
        'It’s as simple as buying things online, choose program, buy online or do a money transfer in the bank, you fill an assessment form which allows us to make a diet plan just for you, and then your assigned mentor will take it from there. Generally, a diet plan is followed for 10 days, you fill the weight tracker every 5 days and on 10th day your mentor plans a totally new diet chart.<br><br>\r\nYou also get the E-kit in the My account section, mentor will regularly send you updates/ guides /tools to cover for your special occasions or situations. This ensures you are supported throughout the program.<br><br>\r\nWe have more than 7000 national and international clients who are doing this globally, every client has a dedicated mentor who studies your assessment form and designs the program. The founder and her senior team monitor every stage.<br><br>\r\nEach client has a private login, your assigned mentor will be in constant touch with you via email chat and most queries are answered within 3 hours, though generally as a rule you should expect a reply to a query within 8 working hours.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (7, 4, 'How would I know which package suits me the best?',
        'You have three options either you use the free health score feature on the home page & answer the questions, it will tell you what is the ideal program for you, if still in doubt use the need assistance feature or you can even chat with us. And don\''t worry whatever program you choose, your mentor will make your diet plan after studying your ASSESSMENT form, she will deploy all necessary tools at her disposal to make your program result oriented. At Balance Nutrition stress is ours not yours.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (8, 4, 'How does this program work?',
        'As soon as you enroll you get a dedicated mentor who is a qualified dietitian, she will plan a personalized diet after reviewing your assessment. Generally, we see that a person should follow a diet for at least 10 days for human body to respond, so we normally send you a new diet on the 10th day, you will be needed to fill your weight tracker every 5 days and other trackers as directed by your mentor. If you may have queries or issues you can send it using the email query in My account section or just mail the mentor directly. ',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (9, 4, 'How our Diet Program works?',
        'One diet plan is for 10 days, during this period if you have queries or issues you can mail your mentor and she will address it within 8 working hours, diet plan is not rigid we adapt it as needed even within every diet cycle. So, in 30 days Program you will get 3 new Diets, 60 days Program you will get 6 new diets and in 90 Days program you will get 9 new Diets.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (10, 4, 'how do I record my progress and update the mentor ?',
        'You should fill the weight in your weight tracker every 5th day in the My account section, other trackers should be filled as recommended by your mentor.<br>\r\nGenerally, the mentor sends a new diet plan on every 10th day but in case needed they will change or modify your diets.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (11, 4, 'Is it necessary to fill the weight tracker & diet recall/food diary ?',
        'The weight tracker has your views and comments, besides your weight statistics.Your mentor will only plan the next diet after reviewing this & the diet recall i.e. the food diary very carefully.<br><br>\r\nThe focus at Balance Nutrition is to plan a diet that fits into your life and make it easy for you, we can only do this with your feedback, the weight tracker and food diary (diet recall) are tools for those feedbacks. Also in any health program its necessary to have comprehensive health records, so one can review/refer to the history whenever there are issues.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (12, 4,
        'Do i need to exercise ? How important is exercise/workout during this program ? How will we lose weight without exercising ?',
        'Most of our clients do not do any form of physical activity due to their busy schedule and yet have managed to lose a good amount of weight. We work on the 80/20 principle of nutrition science. For any weight loss/wellness/fitness program, diet plays 80% role, once you get that right you are bound to get result, if you can exercise and have time for that we may recommend you a suitable physical activity. In certain programs we recommend some physical activity, if so, you should follow the advice of the mentor and she will give you options that suit you.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (13, 4, 'How much weight loss dp you guarantee ?',
        'In any health care program, anywhere in the world there will not be any guarantee, yes, we promise that if you are dedicated follow our diet plan & advice; RESULTS will follow. We have a very high success rate and never seen a client not get result if they follow our advice and are engaged with the mentor. Key is to engage with the mentor for any difficulty as she will do all in her power to make it easy and explain things to you. If that be the case, results are sure.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (14, 4, 'I want to lose weight from the tummy ?',
        'There is no such thing as spot reduction, fat tends to go from areas where it is maximum,but there is no diet in the world which can aim at spot reduction, only surgery can. However, in our program people experience very good inch loss which is visible in our success stories.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (15, 4, 'I have a Wedding/Holiday/Travel coming up? I travel a lot ?',
        'Don’t worry, we have guides such as holiday/travel/wedding, these are tools which allow you to enjoy & still follow the program, the whole program is made with lot of tools to help you go through the program irrespective of such events. That’s our real USP<br>\r\nIn case of any emergencies which simply prevent you from following the program just let the mentor know and she will consider putting your program on hold and grant you an extension.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (16, 4, 'I live in a PG OR a Hostel, can i do the program ?',
        'Yes of course, YOU CAN the whole program is designed for your ease, the diet is personalized for you so all your restrictions or preferences are captured while planning, the dine-out guide has all possible options for you, there are many other tools in the E-kit that makes it possible for you to do the program without getting stressed. Remember it’s our job to fit into your life and not your job to alter your life to fit into our program.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (17, 4, 'How will i maintain the lost weight ?',
        'for your last diet plan we will provide you with maintenance plan which teaches youi how to maintain your results.<BR/>\r\nYou also have a \"lifetime access\" to our recipes and health reads.<BR/>\r\nIn case of premium program client After your last diet, before you leave us, we also provide you  Celebrate Life kit, it has cheat sheets, special daily essentials guide & a realistic menu covering normal day to day life In addition you have 30 day maintenance support.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (18, 5, 'HOW WILL I RECEIVE MY \''ONLINE DIET PLAN\'' ?',
        'Once You have updated your ASSESSMENT, your mentor studies it with the senior team and the founder; if any queries the mentor will mail you, if not a diet chart is send within maximum of 24 hours of getting the form. Your first diet plan will be sent via email and same will be visible in your account on the website.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (19, 5, 'WHAT IS THE PATTERN OF THE DIET, DOES IT NEED SPECIAL FOOD PREPARATION AND HOW STRICT IS IT ?',
        'The ASSESSMENT form has questions like \''who cooks at home\'' and \''how many meals do you eat outside\''. So, the diet plans for losing weight and toning up are totally tailor made, keeping in mind the needs, preferences, restrictions you have, as well as the country of residence. The E-kit has tools & guides which makes the program very flexible and adaptable.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (20, 5, 'CAN I GET A TRIAL SESSION? CAN YOU GIVE ME A SAMPLE DIET ?',
        'We don’t have a trial session or any sample diet; for simple reason that any program like this one needs at least 21 days to see perceptible change, plus, before starting the program we do an extensive assessment only after that a completely custom made diet plan is made & sent to you. We need a minimum commitment of 30 days from you for us to work on you and give results. There is infact no sample diet chart that works for all, what works for you will not work for someone else.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (21, 5, 'DO YOU HAVE CRASH DIETS ?',
        'No genuine program will give any crash diets, that’s a wrong notion and practice, in fact it’s against the core of the science of Nutrition itself.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (22, 5, ' WILL I HAVE TO COOK EXTRA ? IS THERE SPECIAL COOKING OR SPECIAL FOODS ?',
        'At Balance Nutrition, we take a lot of effort initially to assess you & understand your lifestyle, who cooks, what kind of food you have access to, what kind of work lifestyle you have etc.; we make sure that the food given is something you can easily manage given your life and lifestyle, you won\''t be eating or cooking anything that you cannot manage or sustain.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (23, 5, 'DO YOU GIVE POWDERS / SUPPLEMENTS /FANCY INGREDIENTS ?',
        'Eatfit247 is about pure natural foods that you eat and see around you. We don’t use any artificial powders pills or anything which is not natural.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (24, 5, 'WILL I LOOK PALE, HAVE HAIR LOSS ? WILL I FEEL HUNGRY, DULL, AND TIRED AFTER FOLLOWING YOUR PLAN ?',
        'No. We plan your diet considering all nutrition requirements, we ensure that you lose weight but not your health, in fact most of the clients experience a renewed vigor, energy and glow after our program.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (25, 5, 'IS IT A 2 HOUR EATING PATTERN/DO YOU MENTION TIMINGS ?',
        'Before planning your diets, we first consider your lifestyle, what foods are available to you, your work life, and many other things. The diet reaching you will be designed to fit into your life we don\''t give unrealistic diet plans of frequent eating which you cannot sustain.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (26, 6, 'Who do I talk to & How ? HOW WILL MY PROGRAM BE MONITORED ?',
        'After receiving your first diet plan online, your mentor is available for any queries via email. All your queries shall be answered in the shortest time span. It is as quick as 20 minutes. Generally, a diet plan is given every 10th day, if you face any issues in following the diet due to any reason you can tell your mentor and we shall make the necessary changes. This can be done via email chat in the MY Account section.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (27, 6, 'HOW OFTEN DO I TALK TO MY MENTOR ?',
        'During your program at Balance Nutrition, you have unlimited email support with your mentor. All emails are responded to by your mentor within 3 working hours max.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (28, 6, 'CAN I SPEAK TO MY MENTOR ON PHONE ?',
        'Mentors ARE NOT available on phone or WhatsApp. As being a health program a record is mandatory of conversations exchanged as such for all queries/issues email is the best option which goes directly to your assigned mentor and you will get an answer within 3 working hours, However, if you wish to still having any issues, please mail at <strong>eatfit24by7@gmail.com</strong>  and we will take appropriate action.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (29, 6, 'HOW DO I REQUEST A CHAT OR PHONE ?',
        'All you should do is, contact your mentor & send her an email. Post that if you still have issues you can mail them to <strong>eatfit24by7@gmail.com</strong>,  we will review and take appropriate action, if needed a senior person will get on call, Mentors are not allowed to address issues on the phone as we audit all exchanges for quality control.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (30, 7, 'CAN I KNOW THE NUTRITIVE VALUES OF RECIPES ?',
        'Yes, go on recipe section and type the name of the recipe, if it\''s in our bank you shall get the health-o-meter, you can also know the protein, fat, carbohydrate and calorie value of recipes.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0'),
       (31, 7, 'What is Recipe Book ?',
        'You can add your favorite recipe/Recipe mentioned by your mentors in this section. This will work as your personalized recipe book and you don’t have to search same recipe repeatedly.',
        TRUE, current_timestamp, 1, current_timestamp, 1, ':0', ':0');

INSERT INTO mst_program_categories (program_category_id, program_category, url, active, created_at, updated_at,
                                    created_by, modified_by, created_ip, modified_ip)
VALUES (1, 'Weight Loss', 'weight-loss', true, '2017-03-06 00:00:00', '2017-04-01 07:07:27', 1, 1, ':0', ':0'),
       (2, 'Health Plans', 'health-plans', true, '2017-03-06 00:00:00', '2017-04-01 07:07:43', 1, 1, ':0', ':0');

INSERT INTO txn_program_faqs (program_faq_id, program_id, question, answer, active, created_by, modified_by, created_at,
                              updated_at, created_ip, modified_ip)
VALUES (5, 2, 'I have high cholesterol. Will your weight loss program lower it?',
        'Absolutely! Our cholesterol weight loss program is designed to focus on lowering your bad cholesterol by including foods, spice mixes and infused waters. We ensure that you have a \''heart-healthy\'' diet to bring your blood cholesterol within a normal range.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (6, 2, 'Will you give me any supplements for my cholesterol?',
        'No, we only recommend a healthy, balanced diet. We will not give you any other supplements than what your doctor has prescribed. Once your cholesterol level comes down with our diet, you may visit your doctor to alter your medications.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (7, 2, 'Will my cholesterol level stay low even after I complete your program?',
        'As long as you continue eating healthy diet recommended in our program and do mild recommended exercises every day, you will be able to maintain your cholesterol levels within the normal range.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (8, 2, 'Do I have to give up some of my favourite foods?',
        'No, you don\''t have to give up on your favourite foods but you will be strictly monitored by us. You will have to lower the quantity of your favourite foods. You will also have to bring down the quantity of fatty foods from your diet.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (9, 17, 'Are there any side effects I should be aware of?',
        'No, there are no side effects whatsoever. Our programs, our food plans and our spice mixes and infused water are totally natural. They have been created in a simple but effective manner.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (10, 17, 'Can I stop taking the medicines my doctor prescribed me?',
        'You will lose weight with our program and it will lower your blood pressure but you will still have to take medication prescribed by your doctor to be on the safer side. But we can say that your medicine and your dosage will be reduced after you achieve a normal weight through our program.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (11, 17, 'Will your program cause any damage to my body?',
        'No, our programs are completely safe and nature based. And it is with guarantee we say that it will not harm your body. But you need to follow our program religiously or you will not see any improvement.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (12, 17, 'How does your program work?',
        'We start with changing your lifestyle and your food habits, we help you eat a balanced diet, to get your body working we recommend enough but light exercises, and we help you reduce your stress through our expert guidance.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (13, 4, 'Are there any side effects from your program?',
        ' No, there are no side effects from our programs. There are only good results from our program. We only adopt natural methods and recommend only natural foods for your health goal.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (14, 4, 'Do I have to eat less?',
        'No, you don\''t need to eat less and or starve or fast. Our natural, healthy foods and diet plans make sure that you are satiated and refreshed all day long.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (15, 4, 'My weight fluctuates. Do I need to do heavy exercises?',
        'Aah the challenges that Thyroid poses! But the good news is that you don\''t need to do heavy exercises. We recommend exercises that are neither heavy nor tiresome but rather just the right ones.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (16, 4, 'I am always travelling. Can I still reduce my weight?',
        'Of course, you can reduce weight. We have this amazing \''Traveller Menu\'' that is created for this very purpose. We made sure that this menu is suited for people who always love to travel or have to travel.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (17, 6, 'How will it help me?',
        'We use natural methods and personalised diet plans which will help you control high blood pressure, cholesterol and insulin levels. Rather than treating symptoms individually, our natural solutions get to the root of the problem. Our effective herbs help to detoxify your system, reduce bad cholesterol and counteract insulin resistance.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (18, 6, 'Will it improve my other problems like fatigues, hair fall, constipation, irritation etc.?',
        'As you begin your program and follow our detoxification and cleansing step, most of the symptoms subside and disappear from your body. You get to have a lifetime benefit of good health. Our recommended foods and herbs will cleanse your system and keep you refreshed.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (19, 6, 'How soon will I lose weight through your program?',
        'First of all, your body chemistry needs to be transformed in a manner that will lead to a permanent change. To heal the ravages of Syndrome X you must be dedicated in changing your lifestyle. But it takes time, commitment, persistence and patience on your part. Once you make this commitment, you are on your way to free Syndrome X.',
        TRUE, 1, 1, '2017-04-13 00:00:00', '2017-04-13 00:00:00', ':0', ':0'),
       (20, 3, 'How long will it be till I see some results?',
        'First of all, your hormonal imbalance needs to be corrected. You must be firm in changing your lifestyle to heal the damage of PCOS. All it takes is time, commitment, persistence and patience on your part. And slowly, you will see the results. You will be free from acne, you will have regular menstrual cycles, your weight will stabilise.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (21, 3, 'Is PCOS hereditary?',
        'Yes, to some extent PCOS is hereditary. But you need not lose hope and faith. Our weight loss program will try to eliminate your health condition from the core.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (22, 3, 'My weight keeps changing. Is doing heavy exercises necessary?',
        'There is nothing as challenging as PCOS! But, you do not need to do heavy exercises. We recommend light but effective exercises that eliminate the symptoms and heal your body from PCOS.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (23, 3, 'Do I have to stop my medications that my gynaecologist gave me?',
        'No, not at first, however once your hormonal imbalance is corrected and stabilised, you can consult your physician who can alter your medications.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (24, 7, 'I have diabetes. Can you help me?',
        'Yes, we can and we will. If you have diabetes type 2, we advise you right, proper and suitable diet and certain spice mixes and infused waters that balances your sugar levels. But if you have diabetes type 1, as of now, we are not taking it in our program.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (25, 7, 'Do I have to stop my medications during the program?',
        'No, not in the beginning, however once your levels are stable and within the range for a long period of time, your physician can alter your medications.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (26, 7, 'My doctor has already given me a diet. How different is your diet?',
        'Most diets described by doctors are pretty standard. They usually are a list of DOs and DONTs. But at NewMe, your plan will be more nutrient dense and individualized. This approach helps in maintaining your sugar levels faster and better.',
        TRUE, 1, 1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (27, 7, 'Will my sugar levels stay normal even after completing your plan?',
        'Yes, your sugar level will stay normal as long as you continue to follow the advice provided by us.', TRUE, 1,
        1, '2017-04-14 00:00:00', '2017-04-14 00:00:00', ':0', ':0'),
       (28, 8, 'Can I get my cholesterol level any lower by changing my diet?',
        'A good start would be to compile a food diary. Be honest and write down everything you eat over a couple of weeks. Getting a good picture of your normal intake should help you to identify some positive changes you could make.<br/> Cut down on saturated fat wherever possible. Ideally an average woman should not exceed 20g per day (4 teaspoons of butter is around 10g of saturated fat). There are some key cholesterol busting foods that you could try with NewMe. We recommend a cholesterol free diet plan keeping your taste-buds in mind.',
        TRUE, 1, 1, '2017-04-16 00:00:00', '2017-04-16 00:00:00', ':0', ':0'),
       (29, 8, 'How do cholesterol levels change over a lifetime?',
        'It is true that cholesterol levels increase with age, and doctors know it is important to lower our lifetime exposure to cholesterol. So keeping your cholesterol low is important at all ages. As you get older your overall risk of circulatory disease increases. This is partly because of age and also due to other risk factors (high blood pressure, diabetes, weight gain) which may develop over time. Your doctor can explain your risk of having a heart attack and what you might do to reduce the risk. We at NewMe make sure that you maintain your cholesterol levels even after the program is over. We give you Maintenance Guides at the end of the program which can be used for lifetime.',
        TRUE, 1, 1, '2017-04-16 00:00:00', '2017-04-16 00:00:00', ':0', ':0'),
       (30, 8, 'I\''ve had a few tests and my HDL (good cholesterol) is relatively low. How can I increase it?',
        'Having a low HDL-cholesterol and a high triglyceride level is quite common and often happens when the body has difficulty in dealing with dietary fats after a meal. Smoking also depresses HDL-cholesterol. We recommend the following lifestyle approach to raise HDL levels. If you are a smoker it is best to stop. If you carry a lot of excess weight around your waist then losing some of this could help increase your HDL and reduce your triglyceride levels. We will help you in doing this. <br/>\r\nEat a balanced diet based on starchy wholegrain foods with plenty of fruit and vegetables, and low in saturated fat. Opt for cooking oils higher in the monounsaturated fats such as rapeseed oil and olive oil (but use sparingly if overweight) and include nuts and soya regularly.\r\n',
        TRUE, 1, 1, '2017-04-16 00:00:00', '2017-04-16 00:00:00', ':0', ':0'),
       (31, 18, 'I have diabetes. Can you help me?',
        'Yes, we can and we will. If you have diabetes type 2, we advise you right, proper and suitable diet and certain spice mixes and infused waters that balances your sugar levels. But if you have diabetes type 1, as of now, we are not taking it in our program.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (32, 18, 'Do I have to stop my medications during the program?',
        'No, not in the beginning, however once your levels are stable and within the range for a long period of time, your physician can alter your medications.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (33, 18, 'My doctor has already given me a diet. How different is your diet?',
        'Most diets described by doctors are pretty standard. They usually are a list of DOs and DONTs. But at NewMe, your plan will be more nutrient dense and individualized. This approach helps in maintaining your sugar levels faster and better.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (34, 18, 'Will my sugar levels stay normal even after completing your plan?',
        'Yes, your sugar level will stay normal as long as you continue to follow the advice provided by us.', TRUE, 1,
        1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (35, 10, 'Are there any side effects from your program?',
        'No, there are no side effects from our programs. There are only good results from our program. We only adopt natural methods and recommend only natural foods for your health goal.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (36, 10, 'Do I have to eat less?',
        'No, you don\''t need to eat less and or starve or fast. Our natural and health foods and diet plans make sure that you are satiated and refreshed all day long.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (37, 10, 'My weight fluctuates. Do I need to do heavy exercises?',
        'Aah the challenges that Thyroid poses! But the good news is that you don\''t need to do heavy exercises. We recommend exercises that are neither heavy nor tiresome but rather just the right ones.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (38, 10, 'I am always travelling. Can I still reduce my weight?',
        'Of course, you can reduce weight. We have this amazing <strong>Traveller Menu </strong> that is created for this very purpose. We made sure that this menu is suited for people who always love to travel or have to travel.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (39, 12, 'Who would gain from this program',
        'Anyone suffering from recurrent cough & cold allergies, bronchi fever or sinusitis will gain from this program.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (40, 12, 'How can you help?',
        'We give you personalised plans depending on your lifestyle, body type and age. Your everyday diet consists of rich vitamin and mineral antioxidants that will combat the effect of radicals. Also, therapeutic waters and herbs help cleanse your body and improve resistance to diseases.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (41, 12, 'I feel tired all the time. How can you help?',
        'We correct your good pattern to one that is rich in antioxidants. It takes care of the deficiency caused by store, thereby preventing tiredness and irritation. We suggest right quantity of food and herbs that will cleanse your system and help you feel fresh.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (42, 12, 'I am already taking many vitamin A without any success. How would your program help?',
        'If your body is loaded with toxins then no amount of vitamin A can help you. Your body will regain its absorptive power only with detoxification. Detoxification is the first step to all plans. Please check our \"How it works\" page for more information on how we recommend our plans.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (43, 12, 'How different will I feel after the program?',
        'We would love to give you energy of a kid but of course age plays its own role. Once you finish our program, your body will feel lighter and you will be able to perform your daily tasks without feeling tired and fatigued. Your energy level will rise and give you power to work better and faster than before.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (44, 15, 'I have been suffering from gas and acidity for a long time?',
        'It may be because of the food and your lifestyle that interferes with digestion. We at NewMe, identify the root cause and treat it through herbs, therapeutic waters and customised food plan.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (45, 15, 'I take antacids every day ,still my stomach burns everyday. How can you help me?',
        'Antacid gives temporary relief but root cause remains untreated. We use our recommended food as medicine to remove toxins, cleanse and nourish your body.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (46, 15,
        'All my life I had a balanced diet but since two years I have gas and bloating even with the same diet. What is the remedy?',
        'As you age, your nutrients need change and so does your digestion. We therefore suggest a customised plan with natural herbs which will re-energise your whole body.',
        TRUE, 1, 1, '2017-04-17 00:00:00', '2017-04-17 00:00:00', ':0', ':0'),
       (55, 1,
        'I am overweight. Will your program work for me? What if I don\''t lose weight even after following the program?',
        'Our weight loss program will definitely work for you. We have a success rate of 98%. Our approach to weight loss is different from others. It is completely focused and individualised. We start by correcting your eating habits and helping you to eat the right foods. That is why diets recommended by us are 10/10.',
        TRUE, 1, 1, '2018-11-19 13:33:24', '2018-11-19 13:33:24', ':0', ':0'),
       (56, 1, 'Once I start losing weight will my skin sag and become dull, will I have wrinkles?',
        'No, neither will your skin become dull or sag nor will you have any wrinkles. In fact, your skin complexion will improve and will have a angelic glow on it. Our food plan customised for you will be fibre rich, less fatty and nutrient dense.',
        TRUE, 1, 1, '2018-11-19 13:33:24', '2018-11-19 13:33:24', ':0', ':0'),
       (57, 1,
        'I previously enrolled with a dietitian for a weight loss program, lost weight but put it back again. Can you guarantee me positive results?',
        'Our program is not a diet but a complete lifestyle change. When you leave a diet program, you will put on weight. But our weight loss program makes you knowledgeable of your individual body type and the type of food you should eat. Once the knowledge is shared with you, you will never lose your way again and never put on weight. We will be giving free maintenance kits to you for your lifetime so that you remain motivated and never look back to your old life.',
        TRUE, 1, 1, '2018-11-19 13:33:24', '2018-11-19 13:33:24', ':0', ':0'),
       (58, 1, 'Will I lose fat from specific areas?',
        'No, we are truly sad to say this. You cannot lose fat only in your problematic areas. There isn\''t any program of any kind that guarantees spot reduction. It is a gradual process. We help you by recommending the right food and right exercises that reduces the excess fat slowly and in an overall manner. Slowly these problematic areas will start showing effect and you will start to lose weight.',
        TRUE, 1, 1, '2018-11-19 13:33:24', '2018-11-19 13:33:24', ':0', ':0');

INSERT INTO mst_franchises (franchise_id, company_name, first_name, last_name, email_id, alternate_email_id,
                            contact_number, alternate_contact_number, pan_number, tan_number, gst_number, start_date,
                            end_date, active, created_by, modified_by, created_ip, modified_ip, created_at, updated_at,
                            logo)
VALUES (1, 'EATFIT247', 'Shweta', 'Shah', 'eatfit24by7@gmail.com', '', '+919594768888', '', 'AAGFE6471M', '',
        '27AAGFE6471M1ZY', '2017-10-05', null, true, 1, 1, '115.96.212.175', '115.96.212.175', '2017-10-05 14:17:17',
        '2017-10-05 14:17:17', '[]');
insert into txn_addresses (address_type_id, table_id, pk_of_table, postal_address, city_village, state_id, country_id,
                           pin_code, latitude, longitude, active, created_at, created_by, updated_at, modified_by,
                           created_ip, modified_ip)
values (1, 4, 1, '102 - Gemini CHS, Nehru Road', 'Vile Parle (East)', 27, 96, '400057', null, null, true,
        '2017-10-05 14:17:17', 1, '2017-10-05 14:17:17', 1, '115.96.212.175', '115.96.212.175');

INSERT INTO mst_referrers (referrer_id, name, company_name, website_link, logo, franchise_id, active, created_at,
                           updated_at, created_by, modified_by, created_ip, modified_ip, postal_address, state_id,
                           country_id, pin_code, gst_number, tan_number, start_date, end_date, contact_number,
                           alternate_contact_number, alternate_email_id, email_id)
VALUES (1, 'Yasmin Karachiwala', 'Body Image', 'http://www.bodyimage.in/', '[]', 1, true, '2017-10-12 00:00:00',
        '2018-11-20 14:15:26', 1, 1, ':0', ':0', '1st Floor, The Point,Opp. Royal Enfield showroom, 30th Road', 27, 96,
        '400050', '', '', '2017-10-12', null, '+91-8097421877', '+91-8097421877', 'yasmin@gmail.com',
        'yasmin@gmail.com');

insert into txn_addresses (address_type_id, table_id, pk_of_table, postal_address, city_village, state_id, country_id,
                           pin_code, latitude, longitude, active, created_at, created_by, updated_at, modified_by,
                           created_ip, modified_ip)
values (1, 3, 1, '1st Floor, The Point,Opp. Royal Enfield showroom, 30th Road', 'Bandra West', 27, 96, '400050', null,
        null, true,
        '2017-10-05 14:17:17', 1, '2017-10-05 14:17:17', 1, '115.96.212.175', '115.96.212.175');

INSERT INTO mst_pocket_guides (pocket_guide_id, pocket_guide, description, file_path, active, created_at, updated_at,
                               created_by, modified_by, image_path, created_ip, modified_ip)
VALUES (3, 'Cleansing Diet', 'Cleansing Diet', '[]', true, '2017-05-30 00:00:00',
        '2018-08-28 14:36:16', 1, 1, '[]', ':0', ':0'),
       (4, 'De-bloat Powder', 'De-bloat Powder', '[]', false, '2017-06-13 00:00:00',
        '2018-08-28 14:36:57', 1, 1, '[]', ':0', ':0'),
       (5, 'No Salt Diet', 'No Salt Diet', '[]', true, '2017-06-18 00:00:00', '2018-08-28 14:37:42', 1,
        1, '[]', ':0', ':0'),
       (6, 'Restaurant Guide - Non Veg',
        'Heading out for dinner or lunch with friends or family and fear you \''ll will fall off from the weight loss goals ???\r\nNow Keep your both  weight loss goals and social life intact  with our guide to make healthy food choices  that  wont leave you feeling left out .\r\n. ',
        '[]', true, '2017-07-19 00:00:00', '2018-12-28 13:37:40', 1, 1, '[]', ':0', ':0'),
       (7, 'Restaurant Guide Veg',
        'Heading out for dinner or lunch with friends or family and fear you \''ll will fall off from the weight loss goals ???\r\nNow Keep your both  weight loss goals and social life intact  with our guide to make healthy food choices  that  wont leave you feeling left out .\r\n. ',
        '[]', true, '2017-07-19 00:00:00', '2018-12-28 13:36:57', 1, 1, '[]', ':0', ':0'),
       (8, 'Cleansing Juice Day', 'Cleansing Juice Day', '[]', true, '2017-10-23 00:00:00',
        '2018-08-28 14:39:35', 1, 1, '[]', ':0', ':0'),
       (9, 'Detox Diet', 'Detox Diet', '[]', true, '2017-11-02 00:00:00', '2018-08-28 14:40:33', 1, 1,
        '[]', ':0', ':0'),
       (10, 'Post Delivery', 'Post Delivery', '[]', true, '2018-01-22 00:00:00', '2018-08-28 14:41:15',
        1, 1, '[]', ':0', ':0'),
       (11, 'Veg Travel guide', 'Veg Travel guide', '[]', false, '2018-03-15 00:00:00',
        '2018-11-16 14:24:25', 1, 1, '[]', ':0', ':0'),
       (12, 'Healthy Bites',
        'Sometimes you simply get too busy to prepare and eat a healthy meal. Having some healthy snacks on hand can be useful when this happens.',
        '[]', true, '2018-06-05 00:00:00', '2018-12-28 13:31:23', 1, 1, '[]', ':0', ':0'),
       (13, 'Travel guide ',
        'Eating healthy is too hard when you’re traveling because airports are not well-known for healthy food options. Hence it’s very difficult to make good food choices. To help you travel like an expert, Shweta would love to share the golden tips to follow while travelling ',
        '[]', true, '2018-06-11 00:00:00', '2018-12-28 13:29:32', 1, 1, '[]', ':0', ':0'),
       (14, 'Liquid diet', 'Liquid diet ', '[]', true, '2018-06-18 00:00:00', '2018-08-28 15:00:21', 1,
        1, '[]', ':0', ':0'),
       (15, 'Non Veg Travel Guide  Keto', 'Non Veg Travel Guide  Keto', '[]', true,
        '2018-09-26 00:00:00', '2018-09-26 14:55:15', 1, 1, '[]', ':0', ':0'),
       (16, 'Navratri',
        'Navratri is celebrated twice a year and if we notice, every time it falls during the change of season. Change in the seasons has different effects on your physical, mental and spiritual level. By observing fast during this time balances your energy and connects you to the mother goddess.\r\n From an Ayurvedic perspective, eating foods like meat, grains, alcohol, onion, garlic etc. attract and absorb negative energies and should be avoided during a seasonal change when our bodies tend to have low immunity and are more susceptible to fall sick.\r\n',
        '[]', true, '2018-10-03 00:00:00', '2018-12-28 13:24:09', 1, 1, '[]', ':0', ':0'),
       (17, 'Banana Diet', 'Banana Diet', '[]', true, '2018-10-10 00:00:00', '2018-10-10 00:00:00', 1,
        1, '[]', ':0', ':0'),
       (18, 'Veg Travel Guide Keto', 'Veg Travel Guide Keto', '[]', true, '2018-10-10 00:00:00',
        '2018-10-10 00:00:00', 1, 1, '[]', ':0', ':0'),
       (19, 'Maintenance Diet',
        'To improve your chances of permanent weight-loss success, try to incorporate small changes in food choices and   your lifestyle as you move through all phases of the dieting journey.',
        '[]', true, '2018-10-10 00:00:00', '2018-12-28 13:42:09', 1, 1, '[]', ':0', ':0'),
       (20, 'Diwali Guide',
        'Diwali makes for one of the biggest celebrations in the year- and one of the topmost highlights of this extravaganza must be its indulgent sweetmeats, savoury snacks and lavish meals. But before you start digging in, have a look at this essential guide for Diwali celebrations that will may help you make most of the festivities, fun and of course lots of food.\r\n',
        '[]', true, '2018-10-11 00:00:00', '2018-12-28 13:27:53', 1, 1, '[]', ':0', ':0'),

       (21, 'Cheat Sheet',
        'Even though nutrition / weight loss plan are highly personalized, one thing all of us share is the urge to let loose every now and then. It’s impossible to stick to a healthy diet 100 percent of the time.   Whether giving into these cravings helps or hurts you in the long run is largely a matter of How you approach and How much you eat ! \r\n',
        '[]', true, '2018-11-30 00:00:00', '2018-12-28 13:38:57', 1, 1, '[]', ':0', ':0'),

       (22, 'Alcohol Guide',
        'Alcohol can cause weight gain in a couple of ways. While you do not have to cut out all alcohol if you are trying to lose weight, you may need to make some changes. You should watch the number, and type, of drinks you choose. You will also want to keep an eye on how drinking affects your eating habits.This guide will help yo to so .',
        '[]', true, '2018-11-30 00:00:00', '2018-12-28 13:26:12', 1, 1, '[]', ':0', ':0'),

       (23, 'Wedding guide', 'Wedding guide\"', '[]', true, '2019-03-25 00:00:00',
        '2019-03-25 00:00:00', 5, 5, '[]', ':0', ':0'),
       (24, 'Party guide', 'Party guide', '[]', true, '2019-03-25 00:00:00', '2019-03-25 00:00:00', 5,
        5, '[]', ':0', ':0'),
       (25, 'Juice Diet ', 'juice diet', '[]', true, '2021-11-08 00:00:00', '2021-11-08 00:00:00', 5,
        5, '[]', ':0', ':0');
