export enum MediaForEnum {
  RECIPE = 'recipe',
  MEMBER = 'member',
  ADMIN = 'admin',
  PROGRAM = 'program',
  SPECIAL_PLAN = 'special-plan',
  BLOG = 'blog',
  POCKET_GUIDE = 'pocket-guide',
  REFERRER = 'referrer',
  FRANCHISE = 'franchise',

  BLOG_AUTHOR = 'lov/blog-author',
  BLOG_CATEGORY = 'lov/blog-category',
  BLOOD_SUGAR = 'lov/blood-sugar',
  CALL_TYPE = 'lov/call-type',
  CALL_PURPOSE = 'lov/call-purpose',
  URINE_OUTPUT = 'lov/urine-output',
  EATING_HABIT = 'lov/eating-habit',
  GENDER = 'lov/gender',
  HEALTH_PARAMETERS = 'lov/health-parameter',
  LIFESTYLE = 'lov/lifestyle',
  MARITAL_STATUS = 'lov/marital-status',
  NUTRITIVE = 'lov/nutritive',
  RECIPE_CUISINE = 'lov/recipe-cuisine',
  RECIPE_CATEGORY = 'lov/recipe-category',
  RELIGION = 'lov/religion',
  SLEEPING_PATTERN = 'lov/sleeping-pattern',
  TYPE_OF_EXERCISE = 'lov/type-of-exercise',
  PROGRAM_CATEGORY = 'lov/program-category',
}
