export enum StringResources {
  APP_TITLE = 'EatFit247',

  BACK_TO_PREVIOUS_PAGE = 'Back to Previous Page',

  OK = 'Ok',
  CLOSE = 'Close',
  ALERT = 'Alert',
  ARE_YOU_SURE = 'Are you sure?',
  YES = 'Yes',
  INR_SYMBOL = 'INR',
  NO = 'No',
  SEND_OTP = 'Send Otp',
  SEND_MAIL = 'Send Mail',
  CLEAR = 'Clear',
  SEARCH = 'Search',
  SEARCH_FILTER = 'Search Filter',
  SEARCH_TEXT = 'Search text',
  CREATED_AT_FROM_TO_DATE = 'Created From - Created To',
  SAVE = 'Save',
  UPDATE = 'Update',
  CANCEL = 'Cancel',
  DETAILS = 'Details',
  FRANCHISE = 'Franchise',

  ERROR_SOMETHING_WRONG = 'Oppss! Something went wrong',
  NO_INTERNET_TITLE = 'Oppss! Something went wrong',

  CHOOSE_FILE = 'Choose file',
  CHOOSE_ATTACHMENT = 'Choose Attachment',
  TITLE = 'Title',
  RECIPE_NAME = 'Recipe name',
  SERVING_COUNT = 'Serving count',
  TAG_LINE = 'Tag Line',
  PUBLIC = 'Public',
  PRIVATE = 'Private',
  IDEAL_FOR = 'Ideal For',
  DESCRIPTION = 'Description',
  PREPARATION_METHOD = 'Preparation Method',
  INGREDIENTS = 'Ingredients',
  BENEFITS = 'benefits',
  DATE = 'Date',
  TIME = 'Time',
  NAME = 'name',
  START_TIME = 'Start Time',
  END_TIME = 'End Time',
  FIRST_NAME = 'First name',
  LAST_NAME = 'Last name',
  AGE = 'Age',
  DATE_OF_BIRTH = 'Date of Birth',
  TOBACCO = 'Tobacco',
  SMOKING = 'Smoking',
  ALCOHOL = 'Alcohol',
  PAAN = 'Paan',
  FASTING = 'Fasting',
  AREATED_DRINK = 'Areated Drink',
  RESTAURANT_VISIT = 'Restaurant visit',
  WATER_INTAKE = 'Water Intake / Day',
  PREFERRED_CUISINE = 'Preferred Cuisine',
  WHO_COOK = 'Who Cook',
  HUNGER_PEAK_TIME = 'Hunger peak timing',
  FOOD_DISLIKE = 'Food Dislike',
  ANY_FOOD_PREFERENCE = 'Any Food Preference',
  DO_YOU_EXERCISE = 'Do You Exercise',
  DURATION = 'Duration',
  TIMING = 'Timing',
  ALCOHOL_NAME = 'Alcohol name',
  AMOUNT = 'Amount',
  FREQUENCY = 'Frequency',
  ANY_ALLERGIES = 'Any Allergies',
  ALLERGIES_NAME = 'If Yes Specify',
  SLEEPING_DURATION = 'Sleeping Duration',
  GAS = 'Gas',
  HYPER_ACIDITY = 'Hyper Acidity',
  CONSTIPATION = 'Constipation',
  PERIOD_REGULAR = 'Period Regular',
  LMP = 'L.M.P.',
  CYCLE = 'Cycle',
  DAY = 'Day',
  DAYS_CYCLE = 'Days Cycle',
  BACK_PAIN = 'Back Pain',
  KNEE_PAIN = 'Knee Pain',
  HAIR_FALL = 'Hair Fall',
  BLOOD_SUGAR_VALUE = 'Blood Sugar Value',
  LIPID_PROFILE = 'Lipid Profile',
  TOTAL_CHOLESTEROL = 'Total Cholesterol',
  TRIGLYCERIDES = 'Triglycerides',
  HDL_CHOLESTEROL = 'HDL Cholesterol',
  LDL_CHOLESTEROL = 'LDL Cholesterol',
  VLDL_CHOLESTEROL = 'VLDL Cholesterol',
  HEMOGLOBIN_LEVEL = 'Hemoglobin Level',
  MEDICINE_DOSAGE = 'Medicine / Dosage',
  MENU = 'Menu',
  WAKE_UP_TIME = 'Wake Up Time',
  BREAKFAST = 'Breakfast',
  MID_MORNING = 'Mid-Morning',
  LUNCH = 'Lunch',
  EVENING = 'Evening',
  MID_EVENING = 'Mid-Evening',
  DINNER = 'Dinner',
  NIGHT_SNACKS = 'Night Snacks',
  BED_TIME = 'Bed Time',
  FRUITS = 'Fruits',
  BREAD = 'Bread',
  SWEET_CHOCOLATE = 'Sweet / Chocolate',
  TEA_COFFEE = 'Tea / Coffee',
  REMARK = 'Remark',
  NUTRITIONIST_SUMMARY = 'Nutritionist Summary',
  EMAIL_ID = 'Email Id',
  VILLAGE = 'Village',
  ADDRESS_TYPE = 'Address Type',
  ADDRESS = 'Address',
  DISTRICT = 'District',
  LATITUDE = 'Latitude',
  LONGITUDE = 'Longitude',
  CITY_VILLAGE = 'City/Village',
  PIN_CODE = 'Pin Code',
  MESSAGE = 'Message',
  RESPONDED_BY = 'Responded By',
  RESPONDED_MESSAGE = 'Responded Message',
  RESPOND_MESSAGE = 'Respond Message',
  CONTACT_NUMBER = 'Mobile number',
  PASSWORD = 'Password',
  REPEAT_PASSWORD = 'Repeat Password',
  CURRENT_PASSWORD = 'Current Password',
  NEW_PASSWORD = 'New Password',
  OTP = 'Otp (One Time Password)',
  START_DATE = 'Start date',
  WRITTEN_AT = 'Written At',
  END_DATE = 'End date',
  ACTION = 'Action',
  ROLE = 'Role',
  STATUS = 'Status',
  PAYMENT_STATUS = 'Payment Status',
  TAX_APPLICABLE = 'Tax Applicable',
  CURRENCY = 'Currency',
  NO_OF_CYCLE = 'No Of Cycle',
  SEASONAL_PLAN = 'Seasonal Plan',
  TYPE_OF_PLAN = 'Type of plan',
  WEEKLY_PLAN = 'Weekly Plan',
  DAILY_PLAN = 'Daily Plan',
  NEED_TO_PUBLISH_BLOG = 'Need to publish this blog?',
  SHOW_ON_WEBSITE = 'Is Publicly Visible',
  COMMENTING_IS_ALLOW = 'Commenting is allow?',
  MAIL_SEND_TO_SUBSCRIBER = 'Mail send to subscriber?',
  IN_PROGRESS = 'In Progress',
  COMPLETED = 'Completed',
  ACTIVE = 'Active',
  PAID = 'Paid',
  REASON_FOR_STATUS_CHANGE = 'Reason for status change',
  PUBLISHED = 'Published',
  COMMENT = 'Comment',
  NOT_PUBLISHED = 'Not Published',
  IS_LENGTH_UNIT_APPLIED = 'Is Length Unit Applied',
  IN_ACTIVE = 'In-Active',
  PENDING_VERIFICATION = 'Email id verification pending',
  PENDING = 'Pending',
  REASON = 'Reason',
  DRAG_DROP_IMAGE_FILE = 'Drag and drop image file here',
  DRAG_DROP_PDF_FILE = 'Drag and drop pdf file here',
  FROM_TIME = 'From Time',
  TO_TIME = 'To Time',
  SEQUENCE = 'Sequence Number',
  NO_OF_DAYS_IN_CYCLE = 'No of Days in cycle',
  TRANSACTION_NUMBER = 'Transaction number',
  VISIBLE_ON_WEB = 'Visible on Website',
  IS_ONLINE_PLAN = 'Is Online Plan',
  INR_AMOUNT = 'Amount in INR',
  PLAN_AMOUNT = 'Plan Fees',
  DISCOUNT_AMOUNT = 'Discount Amount',
  TAX_AMOUNT = 'TAX Amount',
  TOTAL_AMOUNT = 'Total Amount',
  EXTERNAL_VIDEO_URL = 'External video url',

  PERSONAL_DETAILS = 'Personal Details',
  WORK_DETAILS = 'Work Details',
  EXERCISE_DETAILS = 'Exercise Details',
  MEDICAL_DETAILS = 'Medical Details',
  EATING_PATTERN = 'Eating Pattern',

  LOGIN = 'Login',
  LOGOUT = 'Logout',
  RESET_PASSWORD = 'Reset Password',
  FORGOT_PASSWORD = 'Forgot Password',
  RESEND_OTP = 'Resend OTP',
  BACK_TO_LOGIN = 'Back to Login',
  FORGOT_PASSWORD_NOT = 'Enter your email id, we will send OTP for reset password on your email id, if you do not receive OTP on inbox then check spam folder also',
  RESET_PASSWORD_NOTE = 'Please check your email id for otp, if you don\'t find email on inbox then please check in spam folder also',

  REQUIRED = 'required',
  IN_VALID_NUMBER = 'Invalid number',
  IN_VALID_DATE = 'Invalid date',
  IN_VALID_MAX_LENGTH = 'max length',
  IN_VALID_MIN_LENGTH = 'min length',
  IN_VALID_WEIGHT = 'invalid weight',
  IN_VALID_HEIGHT = 'invalid height',
  IN_VALID_MAX_VALUE = 'Minimum value should be ',
  IN_VALID_MIN_VALUE = 'Maximum value should be ',
  IN_VALID_LATITUDE = 'Maximum value should be ',
  IN_VALID_LONGITUDE = 'Maximum value should be ',

  DELETE_CONTACT_NUMBER_DESC = 'Are you sure, you want to delete this contact number ?',
  CHANGE_STATUS_DESC = 'Are you sure, you want to change status of this item ?',
  RESET_PASSWORD_TITLE = 'Reset Password',
  RESET_PASSWORD_DESC = 'Are you sure, you want to reset password for this user ?',
  SINGLE_MEDIA_FILE_ALERT = 'Only single file upload allow, please delete old one for upload new file',

  MY_PROFILE = 'My Profile',
  ADD_CONTACT_NUMBER = 'Add Contact Number',
  EDIT_CONTACT_NUMBER = 'Edit Contact Number',
  EDIT = 'Edit',
  VIEW_INVOICE = 'View Invoice',
  PREVIEW = 'Preview',
  DELETE = 'Delete',
  ADD = 'Add',
  CREATE_MATRIMONIAL_PROFILE = 'Create Matrimonial Profile',

  COMPANY_NAME = 'Company Name',
  WEBSITE_LINK = 'Website Link',
  ALTERNATE_CONTACT_NUMBER = 'Alternate Contact Number',
  ALTERNATE_EMAIL_ID = 'Alternate Email Id',
  PAN_NUMBER = 'PAN Number',
  TAN_NUMBER = 'TAN Number',
  GST_NUMBER = 'GST Number',

  ADMIN_LIST = 'Admin',
  ADMIN_CREATE = 'Add Admin',
  ADMIN_EDIT = 'Edit Admin',
  CHANGE_PASSWORD = 'Change Password',
  EDIT_PROFILE = 'Edit Profile',

  APP_USER_LIST = 'App User',
  APP_USER_CREATE = 'Add App User',
  APP_USER_EDIT = 'Edit App User',
  DETAIL = 'Detail',
  CONVERSION_HISTORY = 'Conversion History',

  HOME = 'Home',
  MEMBERS = 'Members',
  ASSESSMENT = 'Assessment',
  BASIC_INFORMATION = 'Basic Information',
  BODY_STATS = 'Health Parameters',
  DIET_PLAN = 'Diet Plan',
  RECIPES = 'Recipes',
  DIET_TEMPLATE = 'Diet Templates',
  SPECIAL_PLANS = 'Special Plans',
  PROGRAM_AND_PLAN = 'Program and Plans',
  PROGRAMS = 'Programs',
  PROGRAM = 'Program',
  PLANS = 'Plans',
  PLAN = 'Plan',
  POCKET_GUIDES = 'Pocket Guides',
  SELECT = 'Select',
  HEALTH_ISSUES = 'Health Issues',
  PAYMENT_HISTORY = 'Payment History',
  MEMBER_ISSUES = 'Member Issues',
  MEMBER_HEALTH_ISSUES = 'Member Health Issues',
  CALL_SCHEDULE = 'Call Schedule',
  CONTACT_US = 'Contact Us',
  BLOGS = 'Blogs',
  MEMBER_TESTIMONIAL = 'Testimonial',
  ADMIN_USERS = 'Admin Users',
  REFERRER = 'Referrer',
  NUTRITIONIST = 'Nutritionist',
  COUNTRY_CODE = 'Country Code',
  STATE_CODE = 'State Code',
  PHONE_NUMBER_CODE = 'Phone Number Code',

  QUESTION = 'Question',
  ANSWER = 'Answer',
  FAQS = 'FAQs',
  SETTING = 'Setting',

  LOVS = 'LOVs',
  BLOOD_SUGAR = 'Blood Sugar',
  EATING_HABIT = 'Eating Habit',
  GENDER = 'Gender',
  HEALTH_PARAMETERS = 'Health Parameters',
  LIFESTYLE = 'Lifestyle',
  MARITAL_STATUS = 'Marital Status',
  URINE_OUTPUT = 'Urine Output',
  SLEEPING_PATTERN = 'Sleeping Pattern',
  TYPE_OF_EXERCISE = 'Type Of Exercise',
  RELIGION = 'Religion',
  NUTRITIVE = 'Nutritive',
  RECIPE_CATEGORY = 'Recipe Category',
  RECIPE_CUISINE = 'Recipe Cuisine',
  RECIPE_TYPE = 'Recipe Type',
  CALL_TYPE = 'Call Type',
  CALL_STATUS = 'Call Status',
  CALL_PURPOSE = 'Call Purpose',
  BLOG_CATEGORY = 'Blog Category',
  BLOG_AUTHOR = 'Blog Author',
  TAGS = 'Tags',
  PROGRAM_CATEGORY = 'Program Category',
  FAQ_CATEGORY = 'Faq Category',
  COUNTRY = 'Country',
  STATE = 'State',

  ADD_MEMBER_CALL_LOG = 'Schedule Call',
  EDIT_MEMBER_CALL_LOG = 'Edit Scheduled Call',

  ADD_MEMBER_PAYMENT = 'Payment',
  EDIT_MEMBER_PAYMENT = 'Edit Payment',

  ADD_DIET_PLAN = 'Add Diet Plan',
  EDIT_DIET_PLAN = 'Edit Diet Plan',

  ADD_MEMBER_BODY_STATS = 'Add Body Stats',
  EDIT_MEMBER_BODY_STATS = 'Edit Body Stats',

  ADD_BLOOD_SUGAR = 'Add Blood Sugar',
  EDIT_BLOOD_SUGAR = 'Edit Blood Sugar',

  ADD_EATING_HABIT = 'Add Eating Habit',
  EDIT_EATING_HABIT = 'Edit Eating Habit',

  ADD_GENDER = 'Add Gender',
  EDIT_GENDER = 'Edit Gender',

  ADD_HEALTH_PARAMETERS = 'Add Health Parameters',
  EDIT_HEALTH_PARAMETERS = 'Edit Health Parameters',

  ADD_LIFESTYLE = 'Add Lifestyle',
  EDIT_LIFESTYLE = 'Edit Lifestyle',

  ADD_MARITAL_STATUS = 'Add Marital Status',
  EDIT_MARITAL_STATUS = 'Edit Marital Status',

  ADD_URINE_OUTPUT = 'Add Urine Output',
  EDIT_URINE_OUTPUT = 'Edit Urine Output',

  ADD_PROGRAM_CATEGORY = 'Add Program Category',
  EDIT_PROGRAM_CATEGORY = 'Edit Program Category',

  ADD_FAQ_CATEGORY = 'Add Faq Category',
  EDIT_FAQ_CATEGORY = 'Edit Faq Category',

  ADD_NUTRITIVE = 'Add Nutritive',
  EDIT_NUTRITIVE = 'Edit Nutritive',

  ADD_RECIPE_CATEGORY = 'Add Recipe Category',
  EDIT_RECIPE_CATEGORY = 'Edit Recipe Category',

  ADD_RECIPE_CUISINE = 'Add Recipe Cuisine',
  EDIT_RECIPE_CUISINE = 'Edit Recipe Cuisine',

  ADD_RELIGION = 'Add Religion',
  EDIT_RELIGION = 'Edit Religion',

  ADD_SLEEPING_PATTERN = 'Add Sleeping Pattern',
  EDIT_SLEEPING_PATTERN = 'Edit Sleeping Pattern',

  ADD_TYPE_OF_EXERCISE = 'Add Type Of Exercise',
  EDIT_TYPE_OF_EXERCISE = 'Edit Type Of Exercise',

  ADD_CALL_TYPE = 'Add Call Type',
  EDIT_CALL_TYPE = 'Edit Call Type',

  ADD_CALL_PURPOSE = 'Add Call Purpose',
  EDIT_CALL_PURPOSE = 'Edit Call Purpose',

  ADD_CALL_SCHEDULE = 'Schedule Call',
  EDIT_CALL_SCHEDULE = 'Edit Scheduled Call',

  ADD_BODY_STATS = 'Add Body Stats',
  EDIT_BODY_STATS = 'Edit Body Stats',

  ADD_BLOG_CATEGORY = 'Add Blog Category',
  EDIT_BLOG_CATEGORY = 'Edit Blog Category',

  ADD_BLOG_AUTHOR = 'Add Blog Author',
  EDIT_BLOG_AUTHOR = 'Edit Blog Author',

  ADD_COUNTRY = 'Add Country',
  EDIT_COUNTRY = 'Edit Country',

  ADD_STATE = 'Add State',
  EDIT_STATE = 'Edit State',

  ADD_POCKET_GUIDE = 'Add Pocket Guide',
  EDIT_POCKET_GUIDE = 'Edit Pocket Guide',

  ADD_HEALTH_ISSUE = '̄Add Health Issue',

  ADD_DIET_TEMPLATE = 'Add Diet Template',
  EDIT_DIET_TEMPLATE = 'Edit Diet Template',

  ADD_REFERRER = 'Add Referrer',
  EDIT_REFERRER = 'Edit Referrer',

  ADD_FAQ = 'Add Faq',
  EDIT_FAQ = 'Edit Faq',

  ADD_BLOG = 'Add Blog',
  EDIT_BLOG = 'Edit Blog',

  ADD_RECIPE = 'Add Recipe',
  EDIT_RECIPE = 'Edit Recipe',

  ADD_FRANCHISE = 'Add Franchise',
  EDIT_FRANCHISE = 'Edit Franchise',

  ADD_PROGRAM = 'Add Program',
  EDIT_PROGRAM = 'Edit Program',

  ADD_PROGRAM_PLAN = 'Add Plan',
  EDIT_PROGRAM_PLAN = 'Edit Plan',

  PAYMENT_MODE = 'Payment Mode',
  PAYMENT_DATE = 'Payment Date',
  DOWNLOAD = 'Download',
  INVOICE_NUMBER = 'Invoice Number',
  INVOICE = 'Invoice Details',
  INVOICE_DETAILS = 'Order Summary',
  CGST = 'CGST',
  SGST = 'SGST',
  RESPONSE = 'Response',
  ISSUE_CATEGORY = 'Issue Category',
  ISSUE_STATUS = 'Issue Status',
  ISSUE = 'Issue',
  CHANGE_ISSUE_STATUS_CANCEL_DESC = 'Are you sure, you want to cancel this issue ?',
  CHANGE_ISSUE_STATUS_CLOSE_DESC = 'Are you sure, you want to close this issue ?',

  TOTAL_DIET_SESSIONS = 'Diet Sessions',
  TOTAL_MEMBERS = 'Total Members',
  TOTAL_RECIPES = 'Total Recipes',
  TOTAL_RENEWED_PLAN = 'Total Renewed',
  AVG_PLANS_PER_MONTH = 'Avg. new users',
  AVG_NEW_PLANS_PER_MONTH = 'Avg. new users/month',
  ISSUES_BY_STATUS = 'Issues by status',
  MEMBERS_BY_STATUS = 'Members by status',
  MEMBERS_BY_PROGRAM = 'Members by programs',
  MEMBERS_BY_PLANS = 'Members by plans',
  PAYMENTS_BY_MODE = 'Payments by mode',
  MEMBERS_BY_MONTH = 'Members by month',
  YEAR = 'Year'


}

